DROP TRIGGER IF EXISTS car_trigger_i;
DROP TRIGGER IF EXISTS car_trigger_u;
DROP TRIGGER IF EXISTS invoice_trigger_u;
DROP TRIGGER IF EXISTS invoice_trigger_d;
DROP TRIGGER IF EXISTS model_trigger_i;
DROP TRIGGER IF EXISTS model_trigger_u;
DROP TRIGGER IF EXISTS check_car_availability;
DROP TRIGGER IF EXISTS renting_car;
DROP TRIGGER IF EXISTS finished_rent;